---
- name: "consul-01"
  box:
    vmw: "bento/ubuntu-14.04"
    vb: "ubuntu/trusty64"
  ram: "512"
  vcpu: "1"
  ip_addr: "192.168.1.101"
  role: "consul"
- name: "consul-02"
  box:
    vmw: "bento/ubuntu-14.04"
    vb: "ubuntu/trusty64"
  ram: "512"
  vcpu: "1"
  ip_addr: "192.168.1.102"
  role: "consul"
- name: "consul-03"
  box:
    vmw: "bento/ubuntu-14.04"
    vb: "ubuntu/trusty64"
  ram: "512"
  vcpu: "1"
  ip_addr: "192.168.1.103"
  role: "consul"
- name: "coreos-01"
  box:
    vmw: "coreos-stable"
    vb: "coreos-stable"
  ram: "512"
  vcpu: "1"
  ip_addr: "192.168.1.104"
  role: "docker"
- name: "coreos-02"
  box:
    vmw: "coreos-stable"
    vb: "coreos-stable"
  ram: "512"
  vcpu: "1"
  ip_addr: "192.168.1.105"
  role: "docker"
- name: "coreos-03"
  box:
    vmw: "coreos-stable"
    vb: "coreos-stable"
  ram: "512"
  vcpu: "1"
  ip_addr: "192.168.1.106"
  role: "docker"
