---
- hosts: "all"
  become: "yes"

  tasks:
#  - name: Remove i386 architecture to eliminate apt-get errors
#    command: "/usr/bin/dpkg --remove-architecture i386"

  - name: Install unzip package
    apt:
      pkg: "unzip"
      state: "latest"
      update_cache: "yes"

  - name: Create consul group
    group:
      name: "consul"
      state: "present"

  - name: Create user for Consul
    user:
      name: "consul"
      group: "consul"
      comment: "Consul daemon user"
      shell: "/usr/sbin/nologin"
      state: "present"
      home: "/var/consul"
      system: "yes"
      createhome: "no"

  - name: Create Consul data and configuration directories
    file:
      path: "{{ item }}"
      state: "directory"
      owner: "consul"
      group: "consul"
    with_items:
      - "/var/consul"
      - "/etc/consul.d/server"

  - name: Download Consul package
    get_url:
      url: "https://releases.hashicorp.com/consul/1.2.3/consul_1.2.3_linux_amd64.zip"
      dest: "/tmp/consul_1.2.3_linux_amd64.zip"

  - name: Unzip downloaded Consul file
    unarchive:
      copy: "no"
      src: "/tmp/consul_1.2.3_linux_amd64.zip"
      dest: "/usr/local/bin/"
      creates: "/usr/local/bin/consul"

  - name: Install systemd unit file for Consul
    template:
      src: "consul.service.j2"
      dest: "/etc/systemd/system/consul.service"
      owner: "root"
      group: "root"
      mode: "0644"

  - name: Install Consul configuration file
    template:
      src: "config.json.j2"
      dest: "/etc/consul.d/server/config.json"
      owner: "consul"
      group: "consul"
      mode: "0644"

  - name: Start Consul service
    systemd:
      name: "consul"
      enabled: "yes"
      daemon_reload: "yes"
      state: "started"
