---
- hosts: "all"
  become: "yes"
  remote_user: "vagrant"
  gather_facts: false

  tasks:
  - name: "Install Python 2"
    raw: "apt-get -y -q install python"

  - name: "Install KVM and Libvirt"
    apt:
      state: "present"
      update_cache: "yes"
      name: "{{ item }}"
    with_items:
      - qemu-kvm
      - libvirt-bin
