---
- hosts: "all"
  become: true
  remote_user: "vagrant"
  gather_facts: false

  tasks:
  - name: "Install Python"
    raw: "apt-get -y -q install python"

  - name: "Gather facts"
    setup:

  - name: "Install Kubernetes APT Key"
    apt_key:
      url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
      state: "present"
    tags:
      - manager
      - worker

  - name: "Add Kubernetes repository for Ubuntu Xenial"
    apt_repository:
      repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
      state: "present"
      update_cache: "yes"
    tags:
      - manager
      - worker

  - name: "Install packages for Docker and Kubernetes"
    apt:
      name: "{{ item }}"
      state: "present"
    with_items:
      - "docker.io"
      - "kubectl"
      - "kubelet"
      - "kubeadm"
    tags:
      - manager
      - node
