---
- box:
    vmw: "bento/ubuntu-16.04"
    vb: "bento/ubuntu-16.04"
  name: "xenial"
  nested: false
  nics:
    - type: "private_network"
      ip_addr: "dhcp"
  ram: "512"
  sync_disabled: true
  vcpu: "1"
